In [6]:
import numpy as np
from scipy.optimize import minimize, Bounds

import sympy
from sympy import symbols, hessian, Function, ordered, Matrix, N, init_printing
from sympy.abc import x, y, z
init_printing()

In [7]:
F = x+y+z

v = list(ordered(F.free_symbols)); v
gradient = lambda f, v: Matrix([f]).jacobian(v)
gradient(F, v)

[1  1  1]

In [8]:
def f(x):
    return x[0]+x[1]+x[2]
def grad_f(x):
    return np.array([1,1,1])

constr1 = {'type': 'eq', 
              'fun': lambda x: x[0]**2 + 2*x[1]**2 + 2*x[2]**2 - 8, 
              'jac': lambda x: np.array([2*x[0], 4*x[1], 4*x[2]])}

constr2 = {'type': 'eq',
           'fun': lambda x: x[0]-x[1]+x[2],
           'jac': lambda x: np.array([1,-1,1]) }

In [9]:
bounds = Bounds([-np.inf, -np.inf, -np.inf], [np.inf, np.inf, np.inf])

x0 = np.array([1, 1, 1])

res = minimize(f, x0, method='SLSQP', jac=grad_f, constraints=[constr1, constr2], options={'ftol': 1e-9, 'disp': True}, 
               bounds=bounds)
print(res)

Optimization terminated successfully    (Exit mode 0)
            Current function value: -3.464101615137965
            Iterations: 15
            Function evaluations: 18
            Gradient evaluations: 15
 message: Optimization terminated successfully
 success: True
  status: 0
     fun: -3.464101615137965
       x: [-1.155e+00 -1.732e+00 -5.774e-01]
     nit: 15
     jac: [ 1.000e+00  1.000e+00  1.000e+00]
    nfev: 18
    njev: 15


In [10]:
res.x.round(2)

array([-1.15, -1.73, -0.58])

In [11]:
res.x.round(1)

array([-1.2, -1.7, -0.6])