In [68]:
import numpy as np
from scipy.optimize import minimize, Bounds

import sympy
from sympy import symbols, hessian, Function, ordered, Matrix, N, init_printing
from sympy.abc import x, y, z
init_printing()

In [69]:
F = -x-y*2-3*z

v = list(ordered(F.free_symbols)); v
gradient = lambda f, v: Matrix([f]).jacobian(v)
gradient(F, v)

[-1  -2  -3]

In [70]:
def f(x):
    return -x[0]-x[1]*2-3*x[2]
def grad_f(x):
    return np.array([-1,-2,-3] )

constr1 = {'type': 'eq', 
              'fun': lambda x: 2*x[0]**2 + 2*x[1]**2 + x[2]**2 + 2*x[0]*x[1] - 4, 
              'jac': lambda x: np.array([4*x[0]+2*x[1], 4*x[1]+2*x[0],2*x[2]])}



In [71]:
bounds = Bounds([0,0,0], [np.inf, np.inf,  np.inf])

x0 = np.array([1, 1, 1])

res = minimize(f, x0, method='SLSQP', jac=grad_f, constraints=[constr1], options={'ftol': 1e-9, 'disp': True}, 
               bounds=bounds)
print(res)

Optimization terminated successfully    (Exit mode 0)
            Current function value: -6.633249580714461
            Iterations: 9
            Function evaluations: 10
            Gradient evaluations: 9
 message: Optimization terminated successfully
 success: True
  status: 0
     fun: -6.633249580714461
       x: [ 5.294e-23  6.030e-01  1.809e+00]
     nit: 9
     jac: [-1.000e+00 -2.000e+00 -3.000e+00]
    nfev: 10
    njev: 9


In [72]:
res.x.round(2)

array([0.  , 0.6 , 1.81])

In [73]:
res.x.round(1)

array([0. , 0.6, 1.8])