In [5]:
import numpy as np
import nashpy as nash

In [6]:
A = np.array([ [-0.89, 2.21], [1.44, -0.99], [3.66, 3.66]])
print(A)

[[-0.89  2.21]
 [ 1.44 -0.99]
 [ 3.66  3.66]]


In [7]:
zsg = nash.Game(A)
print(zsg)

Zero sum game with payoff matrices:

Row player:
[[-0.89  2.21]
 [ 1.44 -0.99]
 [ 3.66  3.66]]

Column player:
[[ 0.89 -2.21]
 [-1.44  0.99]
 [-3.66 -3.66]]


In [8]:
P = np.array([0.1, 0.2, 0.7])
Q = np.array([0.4, 0.6])
print(zsg[P,Q])

[ 2.6554 -2.6554]


In [12]:
print(zsg[P, Q].round(2))

[ 2.66 -2.66]
