In [4]:
import numpy as np
from scipy.optimize import linprog
import nashpy as nash

In [5]:
A = np.array([[2, -1, -2], [-1, 0, 2], [0, -2, -1]])
print(A)

[[ 2 -1 -2]
 [-1  0  2]
 [ 0 -2 -1]]


In [6]:
zsg = nash.Game(A)
print(zsg)

Zero sum game with payoff matrices:

Row player:
[[ 2 -1 -2]
 [-1  0  2]
 [ 0 -2 -1]]

Column player:
[[-2  1  2]
 [ 1  0 -2]
 [ 0  2  1]]


In [10]:
nash_eq = zsg.linear_program() # решаем задачи линейного программирования

print('Равновесная смешанная стратегия первого игрока: ', nash_eq[0])

Равновесная смешанная стратегия первого игрока:  [0.25 0.75 0.  ]


In [11]:
c = np.full(shape=3, fill_value=1)
b = np.full(shape=3, fill_value=-1)

shift = 2

res = linprog(c, A_ub=-A.T-shift, b_ub=b)

# цена игры
value1 = 1/res.fun-shift
# равновесная стратегия
P_star = res.x/res.fun

P_star, value1

(array([0.25, 0.75, 0.  ]), -0.25)