In [6]:
import numpy as np
import nashpy as nash

In [7]:
A = np.array([[-2.88, -2.02, -0.42,  2.27], [-3.39,  2.19,  2.56,  0.29], [0.03, -4.51, -3.35, -3.59], [0.50, -1.93,  1.16, -1.02], [0.74,  2.94, -1.96,  1.22]])
print(A)

[[-2.88 -2.02 -0.42  2.27]
 [-3.39  2.19  2.56  0.29]
 [ 0.03 -4.51 -3.35 -3.59]
 [ 0.5  -1.93  1.16 -1.02]
 [ 0.74  2.94 -1.96  1.22]]


In [8]:
zsg = nash.Game(A)
print(zsg)

Zero sum game with payoff matrices:

Row player:
[[-2.88 -2.02 -0.42  2.27]
 [-3.39  2.19  2.56  0.29]
 [ 0.03 -4.51 -3.35 -3.59]
 [ 0.5  -1.93  1.16 -1.02]
 [ 0.74  2.94 -1.96  1.22]]

Column player:
[[ 2.88  2.02  0.42 -2.27]
 [ 3.39 -2.19 -2.56 -0.29]
 [-0.03  4.51  3.35  3.59]
 [-0.5   1.93 -1.16  1.02]
 [-0.74 -2.94  1.96 -1.22]]


In [9]:
# Нижняя цена игры
max( A.min(axis=1) )

-1.93

In [10]:
# Верхняя цена игры
min( A.max(axis=0) )

0.74